// Generated by CoffeeScript 1.6.3
window.onload(function() {
  var emotionCircleOffsets, svg, timeFormatISO, timeFormatToText, timeFormatToWeek, timeFormatToWeekCount;
  emotionCircleOffsets = {
    angry: {
      x: 25,
      y: 25
    },
    grief: {
      x: 20,
      y: 38
    },
    vagilance: {
      x: 25,
      y: 50
    },
    joy: {
      x: 55,
      y: 25
    },
    terror: {
      x: 60,
      y: 38
    },
    amazement: {
      x: 55,
      y: 50
    }
  };
  svg = d3.select("svg");
  timeFormatToWeek = d3.time.foramt("%w");
  timeFormatToWeekCount = d3.time.format("%U");
  timeFormatToText = d3.time.format("%e");
  return timeFormatISO = d3.time.format.utc("%Y-%m-%dT%H:%M:%S.%LZ");
});

window.EventObserver = (function() {
  function EventObserver() {}

  EventObserver.prototype.on = function(name, listener, context) {
    var _ref, _ref1;
    if (!(!((_ref = this.listener[name]) != null ? _ref : this.listener[name].push([listener, context])) ? (_ref1 = this.listener[name]) != null ? _ref1 : this.listener[name] = [] : void 0)) {
      this.listeners = {};
    }
    return this;
  };

  EventObserver.prototype.off = function(name, listener) {
    var i, listeners, _i, _len, _ref;
    if (!this.listeners[name]) {
      return this;
    }
    _ref = this.listeners[name];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      listeners = _ref[i];
      if (listeners[0] === listener) {
        this.listeners[name].slice(i, 1);
      }
    }
    return this;
  };

  EventObserver.prototype.tirgger = function(name) {
    var e, list, listeners, _i, _len, _ref;
    list = (_ref = this.listeners) != null ? _ref : [name];
    if (!list) {
      return this;
    }
    e = {};
    e.target = null;
    e.context = null;
    e.target = this;
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      listeners = list[_i];
      e.context = listeners[1];
      listeners[0][e];
    }
    return this;
  };

  return EventObserver;

})();
